name: deploy

on:
  push:
    branch:
      - master
    paths:
      - 1-flask-deployment/**

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build and Run Docker
      run: docker build -t 1-flask-deployment . && docker run -dp 5001:5001 1-flask-deployment